spring:
  application:
    name: Welcome-Service
  boot:
    admin:
      client:
        url: http://localhost:1111/
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
